spring:
  application:
    name: odMember
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/od_member
    username: root
    password: root
server:
  port: '8081'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka